include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    - public_member_api_docs
    - type_annotate_public_apis
    - recursive_getters